"""empty message

Revision ID: 3dda49a4c08d
Revises: 53a92e3d9700
Create Date: 2015-10-28 19:38:10.313420

"""

# revision identifiers, used by Alembic.
revision = '3dda49a4c08d'
down_revision = '53a92e3d9700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['github_id'])
    op.create_unique_constraint(None, 'tags', ['name'])
    op.create_unique_constraint(None, 'users', ['github_username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    ### end Alembic commands ###
