"""empty message

Revision ID: 4831ce499416
Revises: 79164457ce0
Create Date: 2015-11-03 18:03:40.230217

"""

# revision identifiers, used by Alembic.
revision = '4831ce499416'
down_revision = '79164457ce0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('path', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'path')
    ### end Alembic commands ###
