"""empty message

Revision ID: 53a92e3d9700
Revises: 54a1b58ee90c
Create Date: 2015-10-28 19:21:57.208641

"""

# revision identifiers, used by Alembic.
revision = '53a92e3d9700'
down_revision = '54a1b58ee90c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column(u'articles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column(u'articles', sa.Column('github_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column(u'articles', 'github_id')
    op.drop_column(u'articles', 'author_id')
    op.drop_table('article_tags')
    op.drop_table('users')
    op.drop_table('tags')
    ### end Alembic commands ###
