"""empty message

Revision ID: 79164457ce0
Revises: 3dda49a4c08d
Create Date: 2015-11-02 18:51:58.456802

"""

# revision identifiers, used by Alembic.
revision = '79164457ce0'
down_revision = '3dda49a4c08d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner')
    )
    op.add_column(u'articles', sa.Column('repo_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'articles_github_id_key', 'articles', type_='unique')
    op.create_foreign_key(None, 'articles', 'repos', ['repo_id'], ['id'])
    op.drop_column(u'articles', 'github_id')
    op.add_column(u'users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column(u'users', 'email')
    op.add_column(u'articles', sa.Column('github_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_unique_constraint(u'articles_github_id_key', 'articles', ['github_id'])
    op.drop_column(u'articles', 'repo_id')
    op.drop_table('repos')
    ### end Alembic commands ###
